// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    ChatGpt: typeof import('./src/components/ChatGpt/ChatGpt.vue')['default']
    ContentBox: typeof import('./src/components/TopIndex/components/ContentBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Logo: typeof import('./src/components/TopNav/components/Logo.vue')['default']
    Menu: typeof import('./src/components/TopNav/components/Menu.vue')['default']
    MyElimage: typeof import('./src/components/MyElimage/MyElimage.vue')['default']
    RightInfo: typeof import('./src/components/TopNav/components/RightInfo.vue')['default']
    TopIndex: typeof import('./src/components/TopIndex/TopIndex.vue')['default']
    TopNav: typeof import('./src/components/TopNav/TopNav.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/UploadAvatar.vue')['default']
    VerticalCarousel: typeof import('./src/components/VerticalCarousel/VerticalCarousel.vue')['default']
  }
}

export { }
