// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimeContent: typeof import('./src/components/AnimeContent/AnimeContent.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    ChatGpt: typeof import('./src/components/ChatGpt/ChatGpt.vue')['default']
    ContentBox: typeof import('./src/components/TopIndex/components/ContentBox.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Logo: typeof import('./src/components/TopNav/components/Logo.vue')['default']
    Menu: typeof import('./src/components/TopNav/components/Menu.vue')['default']
    MyElimage: typeof import('./src/components/MyElimage/MyElimage.vue')['default']
    RightInfo: typeof import('./src/components/TopNav/components/RightInfo.vue')['default']
    Search: typeof import('./src/components/TopNav/components/Search.vue')['default']
    SunMoon: typeof import('./src/components/TopNav/components/SunMoon.vue')['default']
    TopArticle: typeof import('./src/components/TopIndex/components/TopArticle.vue')['default']
    TopIndex: typeof import('./src/components/TopIndex/TopIndex.vue')['default']
    TopNav: typeof import('./src/components/TopNav/TopNav.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/UploadAvatar.vue')['default']
    VerticalCarousel: typeof import('./src/components/VerticalCarousel/VerticalCarousel.vue')['default']
    WeatherCard: typeof import('./src/components/TopIndex/components/WeatherCard.vue')['default']
  }
}

export { }
